GET http://localhost:3000/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjFkY2Q1NDhmNDU2N2IzZjhjNjJmZDYiLCJjYXJ0IjpbXSwiaWF0IjoxNjQ2MTI1MjQ5LCJleHAiOjE2NDYyMTE2NDl9.Z_QCFYPrgGblIC8EoOASfMpBeLR1rj5YYn4yb87_x6c


###

DELETE  http://localhost:3000/cart/621cbb9c535b2cbb2f3f5fba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjFjYmI5YzUzNWIyY2JiMmYzZjVmYmEiLCJjYXJ0IjpbXSwiaWF0IjoxNjQ2MDUwNjg3LCJleHAiOjE2NDYxMzcwODd9.NI5Mw7svm8BW7fZAtAi9z3lk08sMmmLuSZq9jyR_7wE

###

POST  http://localhost:3000/cart/621de0642203c19f6df55e16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjFkY2Q1NDhmNDU2N2IzZjhjNjJmZDYiLCJjYXJ0IjpbXSwiaWF0IjoxNjQ2MTQzMzY3LCJleHAiOjE2NDYyMjk3Njd9.-_5BJh5P_Go2PqUwuoTFobBb8ZEh3iHsuP6QEY9dbSg