GET http://localhost:3000/products

###

Post http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjFkY2Q1NDhmNDU2N2IzZjhjNjJmZDYiLCJjYXJ0IjpbXSwiaWF0IjoxNjQ2MTIxNDMwLCJleHAiOjE2NDYyMDc4MzB9.nEKsCKYsBYhCaErHKf2HqWWy4sQAD6yUYsYBeWIThIo

{
"name": " Swiza ",
"price": 5 90000,
"description":"Swiza Plana Women's Watch, Stainless Steel Case, Leather Strap, Quartz, WAT.0921.1005",
"img":" https://i.postimg.cc/fbvYJvx4/women2.jpg"

}

###
DELETE http://localhost:3000/products/621dd4ea556eab845cd04009
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjFkY2Q1NDhmNDU2N2IzZjhjNjJmZDYiLCJjYXJ0IjpbXSwiaWF0IjoxNjQ2MTI0ODk5LCJleHAiOjE2NDYyMTEyOTl9.92LjwOy0i2NhHNfK-BI91ni5CIVktXm2xQhfaf-P0Dg