GET http://localhost:3000/users


###

POST http://localhost:3000/users/signin
Content-Type: application/json
# Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjFjYmI5YzUzNWIyY2JiMmYzZjVmYmEiLCJjYXJ0IjpbXSwiaWF0IjoxNjQ2MTE4ODM4LCJleHAiOjE2NDYyMDUyMzh9._igzmFqXH3xt0PC8czV1D86bnqIZQ3m5f82tLKcDgCY"

{
    "name":"Naruto",

    "password":"sasuke4life"
}


###


DELETE http://localhost:3000/users/
Authorization: Bearer $2b$08$u6ovy3ex6GtVIC67OmDgt.W1HP9vtXFQJfT8oYzp5S/mdNF.dsUt6


###


PATCH http://localhost:3000/users/621cbb9c535b2cbb2f3f5fba
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjFjYmI5YzUzNWIyY2JiMmYzZjVmYmEiLCJjYXJ0IjpbXSwiaWF0IjoxNjQ2MDUwNjg3LCJleHAiOjE2NDYxMzcwODd9.NI5Mw7svm8BW7fZAtAi9z3lk08sMmmLuSZq9jyR_7wE

{
         "name":"Luffy an Zoro"
        
}


